spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bj-cdb-mmv0qh5t.sql.tencentcdb.com:63664/chenji?useUnicode=true&characterEncoding=utf-8
    username: chenji
    password: liwenyu841022
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 60
      initial-size: 60
      max-wait: 1000
      max-wait-thread-count: 100

mybatis:
  type-aliases-package: com.epay.party.building.vote.web.pojo

server:
  port: 9898

cj:
  name: 陈记海参
  url-prefix: /cj/api/
  app-secret: d19f8e8964c9711effa3ff9721df5d41
  app-id: wx71aafc68f6c46172