spring:
  datasource:
    url: jdbc:mysql://bj-cdb-mmv0qh5t.sql.tencentcdb.com:63664/chenji_1?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ENC(+tTY2PicTAmsBWBExofUHVyBF9mNotvU)
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
jasypt:
  encryptor:
    password: joshua
server:
  port: 8083
#  servlet:
#    context-path: /chenji/api
chenji:
  order-length: 5
  order-prefix: CJ

